### ISSUE TITLE
Failed to Install Dependencies in Bankchain

### ISSUE THREAD

**Issue by Payam-Almasian** [PacktPublishing/Blockchain-Development-for-Finance-Projects#48]
Hi 
After Cloning your Github Banckchain Code - I ran NPM Install 
and i get following Error
grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
failed at the grpc 1.24 2 install script
I Use the same version of NODE and NPM as yours

**Comment by JUGERNAUTUS** [comment]
Can you confirm which directory you are running npm install in ?

**Comment by Payam-Almasian** [comment]
In Bankchain Directory 
as you mentioned in README.md

**Comment by JUGERNAUTUS** [comment]
Can you post a complete screenshot of the error and your node-pre-gyp version ?

**Comment by Payam-Almasian** [comment]
root@ubuntu-g1-medium1-at2:/home/ubuntu/Desktop/CODE/fabric-samples/bankchain# npm install

> grpc@1.24.2 install /home/ubuntu/Desktop/CODE/fabric-samples/bankchain/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

/usr/bin/env: ‘node’: Permission denied
npm WARN bankchain@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the grpc@1.24.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-22T13_22_09_411Z-debug.log

**Comment by Payam-Almasian** [comment]
Hi
when I want to instantiate code across the nodes , entered your docker code 

sudo docker exec -e CORE_PEER_LOCALMSPID=bankaMSP -e CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/banka.example.com/users/Admin@banka.example.com/msp cli peer chaincode instantiate -o orderer.example.com:7050 -C bkchannel -n corprem -l node -v 1.0 -c '{"Args":[]}' -P 'AND('\''bankaMSP.member'\'','\''bankbMSP.member'\'')' --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem --peerAddresses peer0.banka.example.com:7051 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/banka.example.com/peers/peer0.banka.example.com/tls/ca.crt

i get the following error 

Error: could not assemble transaction, err proposal response was not successful, error code 500, msg error in simulation: could not launch chaincode corprem:1.0: error starting container: error starting container: API error (404): network _bankchain not found

**Comment by JUGERNAUTUS** [comment]
**Hi,

With respect to the below error using 'sudo' (Superuser access) to invoke the commands might help. The error basically means that you dont have access to the global node repository**

/usr/bin/env: ‘node’: Permission denied
npm WARN bankchain@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! grpc@1.24.2 install: node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the grpc@1.24.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2020-10-22T13_22_09_411Z-debug.log

For the second error, can you paste here the message that you get after you bring the network online using byfnbankchain,sh ?

Thanks

**Comment by deepesh-packt** [comment]
Please reopen if the issue still persists.
