### ISSUE TITLE
Chapter2 running ReactJS app: TypeError App.js line 63

### ISSUE THREAD

**Issue by George2Times** [PacktPublishing/Blockchain-Development-for-Finance-Projects#49]
Hi
#### Issue description
I got: "Unhandled Rejection (TypeError): callbackify is not a function" in ReactJS  app from 'chapter 2'.
I cloned this rep. Followed every instruction from book "Blockchain Development for Finance Projects".
Running with ganache-cli, metamask connected. 

#### Steps to reproduce the issue

1.  Clone rep
2. Follow every instruction from the book 
(there are some smaller issues that are not covered in chapter 2)
3. Run ganache-cli and truffle. 
4. Start app
5. Connect to metamask

#### What's the expected result?
- Smoothly running app

#### What's the actual result?
- ""Unhandled Rejection (TypeError): callbackify is not a function"" in ReactJS app line 63

#### Additional details / screenshot
[](url)
![typeError chapter2](https://user-images.githubusercontent.com/40173066/97293086-771e7d00-184c-11eb-831a-3496993de1f1.png)

**Comment by JUGERNAUTUS** [comment]
Hi, 

Can you confirm the version of web3 available in your nodejs workspace ?

It shouldn't be an issue if web version is 1.2 as per the package.json file.

**Comment by George2Times** [comment]
ubuntu@t2:~/Blockchain-Development-for-Finance-Projects/Chapter2/Chapter2/tokenwallet$ npm ls web3
token-wallet@1.0.0 /home/ubuntu/Blockchain-Development-for-Finance-Projects/Chapter2/Chapter2/tokenwallet
└── web3@1.3.0 

tokenwallet/package.json
{
  "name": "token-wallet",
  "version": "1.0.0",
  "private": false,
  "dependencies": {
    "bulma-start": "0.0.2",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "react-scripts": "1.1.4",
    "sha3": "^2.1.3",
    "web3": "^1.2.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

**Comment by JUGERNAUTUS** [comment]
Can you switch over to web3.js 1.2 from 1.3 ? The issue should be resolved then.  

The 1.3 version seems to have been updated.

Alternatively if you are using just ganache for running the wallet, you can hardcode the networkName parameter to "localhost" as the function that erroring is only for "aesthetic value".

There might be other web3 functions that do not behave as expected due to the version change. So I would recommend switching to 1.2

**Comment by George2Times** [comment]
I switched to web3 1.2. It worked but 

I can not see tokens in wallet app

![Screenshot_1](https://user-images.githubusercontent.com/40173066/97600090-feb0eb00-1a08-11eb-8fb1-622573a9ed36.png)
There is some error with web3/module
![Screenshot_2](https://user-images.githubusercontent.com/40173066/97600096-007aae80-1a09-11eb-80bd-0f3841ec97b1.png)
![Screenshot_3](https://user-images.githubusercontent.com/40173066/97600111-03759f00-1a09-11eb-9c80-fd0d28e9fcd2.png)

Additional info:
I use remote ubuntu LTS 18 as server. I am connected with ssh. 
Ganache-cli, truffle running on ubuntu, app in Visual Studio Code (with ssh connection). Metamask on local (win10) firefox.
I am forwarding 8545 port using:
ssh -i "<private_key_file>" -N -v ubuntu@52.157.82.75 -L 8545:localhost:8545

**Comment by JUGERNAUTUS** [comment]
Can you let me know the web3 method being called and the calling parameters when you get this error ?

**Comment by George2Times** [comment]
There are 2 errors that have one thing in common:
1. App.js:425	Tokens20.forEach((token) => {
2. App.js:463	Tokens721.forEach((token721) => {

Tokens20 list have 1 opbject:
0: Object { address: "0x549932f300bb6807f174EcFa41a1C34aB3f64440", decimal: 4, name: "MoolahCoin", … }
And Tokens721 have 1 opbject:
0: Object { address: "0xB1a54A6dB263374120C5B3A00184542812B6D25D", decimal: 0, name: "Condos", … }

Where truffle output:

Deploying 'MoolahCoin'
   ----------------------
   > transaction hash:    0x94846a6c9acbfbfbf5f0001df963eed179b647b5078082fa792662c1bc25693b
   > Blocks: 0            Seconds: 0
   > contract address:    0xdfE05159929219e74569eb1c388007D25Bf05c5a
   > block number:        5
   > block timestamp:     1604150352
   > account:             0xA96577606De309D5873105DC0F20260DbA3CfFdF
   > balance:             99.90995318
   > gas used:            1873777 (0x1c9771)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.03747554 ETH



Deploying 'Condos'
   ------------------
   > transaction hash:    0x66bdd69a2e21f392c72ffa052e622115429a67c6b0e1c84120aa7aa9eed3f422
   > Blocks: 0            Seconds: 0
   > contract address:    0x7355DFeD98866eEE064B7E6eCd01aA20c4559382
   > block number:        3
   > block timestamp:     1604150352
   > account:             0xA96577606De309D5873105DC0F20260DbA3CfFdF
   > balance:             99.9479762
   > gas used:            2368841 (0x242549)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.04737682 ETH


Wallet accout address is correct: 0xa96577606de309d5873105dc0f20260dba3cffdf

but tokens addresses are diffrent:
MoolahCoin			
**0x549932f300bb6807f174EcFa41a1C34aB3f64440 (App.js Tokens20)**
contract address:	
**0xdfE05159929219e74569eb1c388007D25Bf05c5a (truffle)**
Codos 				
**0xB1a54A6dB263374120C5B3A00184542812B6D25D (App.js Tokens721)**
contract address:	
**0x7355DFeD98866eEE064B7E6eCd01aA20c4559382 (truffle)**

Next is executed for each token:
>let erc20Token = new this.web3.eth.Contract(token.abi,token.address); 
erc20Token.methods.balanceOf(account).call().then(function(response){ <-Here I am getting an error

Error erc20Token stack (erc721Token looks the same)
next is called send from web3
![stack](https://user-images.githubusercontent.com/40173066/97782353-58dcb800-1b91-11eb-82d3-346e2a2d0772.png)

**Comment by JUGERNAUTUS** [comment]
1. Can you log the value of account and the add a catch block to log the error and share it here?
 
"erc20Token.methods.balanceOf(account).call().then(function(response){ <-Here I am getting an error"


2. Im sorry but I couldnt understand the below. Ideally you should have one wallet address (From metamask), one contract address for Moolah Coin token and one contract address for Condos token. Let me know if this doesnt match with what you have. Thanks

"Wallet account address is correct: 0xa96577606de309d5873105dc0f20260dba3cffdf

but tokens addresses are different:
MoolahCoin
0x549932f300bb6807f174EcFa41a1C34aB3f64440 (App.js Tokens20)
contract address:
0xdfE05159929219e74569eb1c388007D25Bf05c5a (truffle)
Codos
0xB1a54A6dB263374120C5B3A00184542812B6D25D (App.js Tokens721)
contract address:
0x7355DFeD98866eEE064B7E6eCd01aA20c4559382 (truffle)"

**Comment by deepesh-packt** [comment]
Please reopen the issue still persists.
Thanks!
