### ISSUE TITLE
Chapter 5: gulp build is not available task, try running: gulp --tasks (tried to run: node CrateAccount.js)

### ISSUE THREAD

**Issue by George2Times** [PacktPublishing/Blockchain-Development-for-Finance-Projects#50]
Hi
#### Issue description
I tried to run:
ubuntu@t2:~/Blockchain-Development-for-Finance-Projects/Chapter 5/node_modules/stellar-sdk$ npm install
Got 
> ubuntu@t2:~/Blockchain-Development-for-Finance-Projects/Chapter 5/node_modules/stellar-sdk$ npm install
> stellar-sdk@6.2.0 prepare /home/ubuntu/Blockchain-Development-for-Finance-Projects/Chapter 5/node_modules/stellar-sdk
> gulp build
> [13:12:43] Using gulpfile ~/Blockchain-Development-for-Finance-Projects/Chapter 5/node_modules/stellar-sdk/gulpfile.js
> [13:12:43] Task never defined: build
> [13:12:43] To list available tasks, try running: gulp --tasks
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! stellar-sdk@6.2.0 prepare: `gulp build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the stellar-sdk@6.2.0 prepare script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/ubuntu/.npm/_logs/2020-10-30T13_12_43_360Z-debug.log

#### Steps to reproduce the issue

1. Clone rep
2. Follow every instruction from the book
3. Try to run 
![Screenshot_5](https://user-images.githubusercontent.com/40173066/97710051-86efc880-1abb-11eb-825e-40e29f8b078d.png)

3. Run: cd 'Chapter 5/node_modules/stellar-sdk'
4. Run: npm install

#### Additional details / screenshot
![Screenshot_4](https://user-images.githubusercontent.com/40173066/97709865-4b54fe80-1abb-11eb-83cb-d96c857bffe2.png)

It is possible to add 'build' function to gulpfile.js
>var gulp = require('gulp');
>gulp.task('build', function () { 
>    console.log('Hello Gulp!') 
>});

But to what write in the 'build' function body?

**Comment by JUGERNAUTUS** [comment]
Hi,

For installing the stellar sdk, please create a new nodejs project workspace and run the following command

npm install --save stellar-sdk

**Comment by George2Times** [comment]
I did:
1. cd '~/Blockchain-Development-for-Finance-Projects/Chapter 5'
2. npm init
3. npm install --save stellar-sdk

>package.json :
{
  "name": "chapter-5",
  "version": "1.0.0",
  "description": "",
  "main": "CreateAccount.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "stellar-sdk": "^6.2.0"
  }
}
4. node CreateAccount.js
and got:
>internal/modules/cjs/loader.js:463
  throw e;
  ^
Error: Package exports for '/home/ubuntu/Blockchain-Development-for-Finance-Projects/Chapter 5/node_modules/tslib' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:460:13)
    at resolveExports (internal/modules/cjs/loader.js:393:16)
    at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ubuntu/Blockchain-Development-for-Finance-Projects/Chapter 5/node_modules/stellar-sdk/lib/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10) {
  code: 'MODULE_NOT_FOUND'
}

node -v 13.0.1, stellar-sdk -v 6.2.0
File:
>CreateAccount.js  :
const StellarSdk = require('stellar-sdk')
const server = new StellarSdk.Server('http://127.0.0.1:8000', {allowHttp: true});
const passphrase =  'Standalone Network ; February 2017'
const MasterKey = StellarSdk.Keypair.master(passphrase)
const MasterSecret = MasterKey.secret();
const MasterPublicKey = MasterKey.publicKey();
console.log ('Master Account',MasterSecret, MasterPublicKey);
const pair1 = StellarSdk.Keypair.random(passphrase);
const pair2 = StellarSdk.Keypair.random(passphrase);
const pair3 = StellarSdk.Keypair.random(passphrase);
var SecretKey1 = pair1.secret();
var PublicKey1 = pair1.publicKey();
console.log ('Account1',SecretKey1, PublicKey1);
var SecretKey2 = pair2.secret();
var PublicKey2 = pair2.publicKey();
console.log ('Account2',SecretKey2, PublicKey2);
var SecretKey3 = pair3.secret();
var PublicKey3 = pair3.publicKey();
console.log ('Account3',SecretKey3, PublicKey3);
(async function main() {
const account = await server.loadAccount(MasterPublicKey);
const fee = await server.fetchBaseFee();
 const transaction = new StellarSdk.TransactionBuilder(account, { fee, networkPassphrase: passphrase})
        .addOperation(StellarSdk.Operation.createAccount({
				source: MasterPublicKey,
                destination: PublicKey1,
                startingBalance: "100000"  
            }))
		.addOperation(StellarSdk.Operation.createAccount({
				source: MasterPublicKey,
                destination: PublicKey2,
                startingBalance: "100000"
            }))
		.addOperation(StellarSdk.Operation.createAccount({
				source: MasterPublicKey,
                destination: PublicKey3,
                startingBalance: "100000"
            }))	
        .setTimeout(30)
        .build();
transaction.sign(MasterKey);
    try {
        const transactionResult = await server.submitTransaction(transaction);
        console.log(transactionResult);
    } catch (err) {
        console.error(err);
		    }
})()

**Comment by JUGERNAUTUS** [comment]
Hmm...from what I understand this seems to be an error when there is a discrepancy in node versions

https://stackoverflow.com/questions/64527465/error-package-exports-for-tslib-do-not-define-a-valid-target

However since we both have the same Nodejs version I dont understand the challenge here.

Maybe you can use nvm to toggle the next versions? (upgrade /degrade) and see what works? Or do a fresh node environment setup. Alternatively see if it works on different machine with Nodejs so we can isolate if the problem is an environmental issue or something else

**Comment by George2Times** [comment]
Thank you.
Downgraded to v12.19.0 -> It worked.

**Comment by JUGERNAUTUS** [comment]
Awesome
