### ISSUE TITLE
chapter-2: the App seems to be incomplete

### ISSUE THREAD

**Issue by ATHULYA-95** [PacktPublishing/Blockchain-Development-for-Finance-Projects#52]
![Screenshot from 2020-12-09 23-18-46](https://user-images.githubusercontent.com/69070553/101667702-aba16d80-3a75-11eb-9a90-83c5b1827d22.png)
![Screenshot from 2020-12-09 23-18-46](https://user-images.githubusercontent.com/69070553/101667742-b5c36c00-3a75-11eb-8336-94980271cd2c.png)

**Comment by JUGERNAUTUS** [comment]
Athulya, Can you confirm if you have signed into Metamask and given the app access to the accounts? Ideally the ethereum account number should be displayed in ETH Account

**Comment by athulya-9** [comment]
yes!! I have signed into metamask and did the needfull...

**Comment by JUGERNAUTUS** [comment]
Can you send a screenshot of your Metamask wallet? And also confirm the steps till which you have finished execution as of this screenshot

**Comment by JUGERNAUTUS** [comment]
Please also check the browser console for any error messages. To do so on Chrome browser, right click and select inspect. In the window frame that opens, go to the Console tab and check any error messages

**Comment by ATHULYA-95** [comment]
![Screenshot from 2021-01-07 19-47-23](https://user-images.githubusercontent.com/69070553/103903271-b22d0e80-5121-11eb-8d46-a9cfcf4d3247.png)

![Screenshot from 2021-01-07 19-52-16](https://user-images.githubusercontent.com/69070553/103903418-dee12600-5121-11eb-85a4-b398dab73691.png)
Hello Sir!! In the first Screenshot this error is coming up, but when I reload it is showing as in the second screenshot. After sometime it again shows this error. :(

**Comment by JUGERNAUTUS** [comment]
Hi Athulya,

Can you send me the first screenshot without metamask covering the error message ?

Please also confirm your web3 version

Thanks

**Comment by ATHULYA-95** [comment]
![Screenshot from 2021-01-08 12-04-29](https://user-images.githubusercontent.com/69070553/103982694-f8c64b80-51a9-11eb-925f-7d2cb340fb49.png)

Sir, The web3 version is 1.3.0

**Comment by JUGERNAUTUS** [comment]
Can you check if the token ABI file (./Tokens/all20) is imported correctly and the ERC20 token is deployed to ganache ?

**Comment by ATHULYA-95** [comment]
account = accounts[0];
this.web3.eth.defaultAccount = account ; --- account variable is set correctly. 
Sir I had deployed ERC20 token to ganache properly. I did transfer through metamask and was successful.

**Comment by ATHULYA-95** [comment]
![Screenshot from 2021-01-11 21-59-46](https://user-images.githubusercontent.com/69070553/104210592-153bdf80-5459-11eb-8611-3beb4a3710c7.png)
Condos part worked now!! Still struggling with Moolahcoin

**Comment by JUGERNAUTUS** [comment]
Can you check if you have any error msgs for Mollahcoin on the console ? Remember you have to mint the tokens to your address to view them in the wallet, for both Moolahcoin and Condos

**Comment by ATHULYA-95** [comment]
Sir.. I think after migrating I pasted the wrong address in MoolahCoin. How can I redo that?

**Comment by JUGERNAUTUS** [comment]
You can get the address from the console logs in ganache GUI. It'll be like below 

Transaction: 0xc2471aa6d1e020921d41247ac2a86eb5ad2447e93450347365a25f8d632e34bd
Contract created: 0x98445ab3eaafdd2293981525631730c64adec41a // <--- contract address
Gas usage: 245439
Block Number: 20
Block Time: Thu Dec 28 2020 20:43:11 GMT+ 0530 (+08)

Alternatively, you can invoke the contract instance and paste the address

var MoolahCoin = artifacts.require("./MoolahCoin.sol");

module.exports = function(deployer) {
    MoolahCoin.deployed())
    .then(_instance => console.log(_instance.address));
};

**Comment by ATHULYA-95** [comment]
It worked sir!!! Thank you so much sir. :)

**Comment by JUGERNAUTUS** [comment]
Awesome

**Comment by JUGERNAUTUS** [comment]
Closing as issue is resolved
